// react/react-saml/src/App.tsx
import { useIDMesh } from 'idmesh-react';
import React, { useEffect, useState } from 'react';


function App() {
  const { loginWithRedirect, logout, isAuthenticated, user, isLoading, getAccessTokenSilently } = useIDMesh();
  const onLogin = () => loginWithRedirect();
  const onLogout = () => logout({ logoutParams: { redirect_uri: window.location.origin } });
  const userInfoString = JSON.stringify(user, undefined, 4);
  const [accessToken, setAccessToken] = useState('');

  useEffect(() => {
    const getToken = async () => {
      setAccessToken(await getAccessTokenSilently());
    };
    if (isAuthenticated) {
      getToken();
    } else {
      setAccessToken('');
    }
  }, [isAuthenticated, getAccessTokenSilently]);

  return (
    <>
      <h1>
        Hello IDMesh
      </h1>
      <button onClick={onLogin} disabled={isLoading || isAuthenticated}>Login In</button>
      <button onClick={onLogout} style={{ marginLeft: '6px' }} disabled={isLoading || !isAuthenticated}>Log Out</button>
      { isLoading && <div>loading...</div>}
      {
        accessToken && (<>
         <h2>Access Token:</h2>
          <pre>{ accessToken }</pre>
        </>)
      }
      {
        isAuthenticated && (<>
         <h2>User Info:</h2>
          <pre>{ userInfoString }</pre>
        </>)
      }
    </>
  );
}

export default App;

// vue/vue-saml/src/App.vue
<script setup lang="ts">
import { useIDMesh } from 'idmesh-vue';
import { watch, ref, unref } from 'vue';

const { loginWithRedirect, user, isAuthenticated, logout, isLoading, getAccessTokenSilently } = useIDMesh();
const accessToken = ref('');

watch(() => unref(isAuthenticated), async (v: boolean) => {
  if (v) {
    accessToken.value = await getAccessTokenSilently();
  } else {
    accessToken.value = '';
  }
}, { immediate: true });

const onLogin = () => loginWithRedirect();
const onLogout = () => {
  logout({ logoutParams: { redirect_uri: window.location.origin } });
};
</script>

<template>
  <div>
    <h1>Welcome to IDMesh</h1>
    <button @click="onLogin" :disabled="isLoading || isAuthenticated" :style="{ marginRight: '6px' }">Log in</button>
    <button @click="onLogout" :disabled="isLoading || !isAuthenticated">Log out</button>
    <div v-if="isLoading">loading...</div>
    <template v-if="accessToken">
      <h2>Access Token:</h2>
      <pre>{{ accessToken }}</pre>
    </template>
    <template v-if="isAuthenticated">
      <h2>User Info:</h2>
      <pre>{{ user }}</pre>
    </template>
  </div>
</template>

<style scoped>
</style>
